"""
Django settings for sqlserverconnect project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from pathlib import Path
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3jk9lixnct-&vqca&nwm)k8g#q#l4lffaru!=9a#q+nudd=5-$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1', '[::1]', '']
CSRF_TRUSTED_ORIGINS = ['https://web-production-185f7.up.railway.app','https://*.127.0.0.1']




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wb2',
    'paypal.standard.ipn'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware',
]



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',
]

ROOT_URLCONF = 'wb2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wb2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'jewelry',          
#         'USER': 'root',
#         'PORT': '3306',
#         'PASSWORD': 'olemiss2024',
#         'HOST': '127.0.0.1',
#          }, 
#     }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway',
        'USER': 'root',
        'PORT': '10374',
        'PASSWORD': 'ouqEbDMHGOPRTmHzBHFaoJgIzpqkpjIF',
        'HOST': 'monorail.proxy.rlwy.net',
         }, 
    }



# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}


REMOTE_USER_HEADER = 'HTTP_REMOTE_USER'

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT = 'C:/Users/sukh1/Downloads/Senior_project_jewelry'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

PROJECT_ROOT = os.path.normpath(os.path.dirname(__file__))
STATICFILES_DIRS = [
    os.path.join(PROJECT_ROOT, '..', 'static'),
]

# settings.py

# LDAP
LDAP_AUTH_URL = "ldap://your-ldap-server.com:389"  # Replace with your server

LDAP_AUTH_USE_TLS = False  # Change to True if using TLS

LDAP_AUTH_SEARCH_BASE = "ou=users,dc=example,dc=com"  # Replace with your base DN

# The LDAP class that represents a user.
LDAP_AUTH_OBJECT_CLASS = "user"  # Change if using a different class

# User model fields mapped to the LDAP
# attributes that represent them.

# settings.py

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PAYPAL_CLIENT_ID  = "AYK5JEsWGBRcht58ghlPkzdZYyYbVgZdxWPrP9S6jdLaTtEjHQGVaU7MMaU55mEmaw2KrSR1zauIkzt2"
PAYPAL_SECRET_ID  =  "ECK03cxrvEBx3RknGaESqilz9MpjUuljqTZZxr6u7AEjheGXJZNUGMppta1asvo6dy-PPKN8DdI8gtGT"

PAYPAL_RECEIVER_EMAIL = 'bizprocipherm@gmail.com'
PAYPAL_TEST = True